services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Coordinador123
      MYSQL_DATABASE: ControlEscolarDB
      MYSQL_USER: Coordinador
      MYSQL_PASSWORD: Coordinador123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Montaje del archivo de inicialización

volumes:
  db_data: